source 'https://rubygems.org'

gem 'sinatra', '1.4.4'
gem 'sinatra-contrib', '1.4.2'

group :test do
  gem 'rspec', '3.2.0'
  gem 'rake', '10.2.2'
  gem 'simplecov', '0.8.2'
  gem 'rack-test', '0.6.2'
end
