source 'https://rubygems.org'

gem 'sinatra', '1.4.6'
gem 'sinatra-contrib', '1.4.2'

group :test do
  gem 'rspec', '3.2.0'
  gem 'rake', '10.4.2'
  gem 'simplecov', '0.9.2'
  gem 'rack-test', '0.6.3'
end
